---

# - name: Include OS-specific variables.
#   include_vars:
#     file: "{{ item }}"
#   with_first_found:
#     - "{{ ansible_distribution | lower }}.{{ ansible_lsb.codename | lower }}.yml"
#     - "{{ ansible_distribution | lower }}.{{ ansible_lsb.major_release }}.yml"
#     - "{{ ansible_distribution | lower }}.yml"
#     - "{{ ansible_os_family | lower }}.yml"
#     - "default.yml"

- name: ensure additional packages are installed
  package:
    name: "{{ common_additional_packages }}"
    state: present

- name: ensure needed packages are installed
  package:
    name: "{{ common_default_packages }}"
    state: present

- name: disable IPv6
  copy:
    # state: present
    dest: /etc/sysctl.d/10-disable-ipv6.conf
    mode: 0640
    content: |
      net.ipv6.conf.all.disable_ipv6 = 1
  when: common_disable_ipv6

- include_tasks: fqdn.yml

- name: set timezone to {{ timezone }}
  # become: true
  timezone:
    name: "{{ common_timezone }}"
  # no_log: true
  ignore_errors: true

- name: Make sure Ansible local facts directory exists
  file:
    dest: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'


- name: add subdomains to /etc/hosts
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
  when: custom_hosts is defined and custom_hosts | count != 0

- name: update /root/.bash_profile
  template:
    src: bash_profile.j2
    dest: /root/.bash_profile
