---
- hosts: all
  any_errors_fatal: false
  environment:
    NETRC: ''
  roles:
    - role: common

  # pre_tasks:
  #   - debug:
  #       var: "{{ item }}"
  #     when: item is defined
  #     loop:
  #       - ansible_os_family
  #       - ansible_distribution
  #       - ansible_lsb.codename
  #       - ansible_lsb.major_release
  #       - ansible_distribution_major_version
